version: "3.6"

services:

  # Wordpress auto configuration
  # depends on wp-cli build
  wp-core-install:
    image: wpcli
    build: ./
    container_name: ${COMPOSE_PROJECT_NAME}_wp_core_install
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - wordpress:/var/www/html
      - ${THEME_LOCAL_DIR:-./mytheme}:/var/www/html/wp-content/themes${THEME_CONTAINER_DIR:-/mytheme}
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - mysql
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=mysql:3306,wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-en_US}
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL:-"http://localhost"}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL:-localhost}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER:-wordpress}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-wordpress}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-"test@example.com"}
      - WORDPRESS_TIMEZONE=${WORDPRESS_TIMEZONE:-"America/New_York"}
      - WORDPRESS_PERMALINKS_STRUCTURE=${WORDPRESS_PERMALINKS_STRUCTURE:-"/%postname%/"}
      - THEME_FOLDER=${THEME_FOLDER:-mytheme}
      - PLUGINS_TO_INSTALL=${PLUGINS_TO_INSTALL:-wordpress-importer}
