<?php

add_filter( 'acf/load_field/key=field_59a466652cc4c', 'vdv_populate_adrotate_groups' );
add_filter( 'acf/load_field/key=field_59c1993abdf17', 'vdv_populate_adrotate_groups' );
add_filter( 'acf/settings/show_admin', 'vdv_show_acf_admin' );

function vdv_populate_adrotate_groups( $field ) {
	$field['choices'] = vdv_get_adrotate_groups();
	return $field;
}

function vdv_show_acf_admin() {
	$current_user = wp_get_current_user();
	return 'rdourado' === $current_user->user_login;
}

function vdv_get_adrotate_groups() {
	$values = get_transient( 'adrotate_groups' );
	if ( false === $values || empty( $values ) ) {
		global $wpdb;
		$values  = array();
		$results = $wpdb->get_results( "SELECT `id`,`name` FROM {$wpdb->prefix}adrotate_groups ORDER BY `id` ASC" );
		foreach ( $results as $row ) {
			$values[ $row->id ] = $row->name;
		}
		set_transient( 'adrotate_groups', $values, 1 * HOUR_IN_SECONDS );
	}
	return $values;
}

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5986547a15f31',
			'title'                 => 'Autor',
			'fields'                => array(
				array(
					'key'               => 'field_598654abfeb78',
					'label'             => 'Bio',
					'name'              => 'bio',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'user_form',
						'operator' => '==',
						'value'    => 'edit',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_59a45d23410d3',
			'title'                 => 'Página inicial',
			'fields'                => array(
				array(
					'key'               => 'field_59a45d350f2e4',
					'label'             => 'Destaques Principais',
					'name'              => 'vdv_highlights',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 1,
					'max'               => 5,
					'layout'            => 'table',
					'button_label'      => '+',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59a45d580f2e5',
							'label'             => 'Artigos',
							'name'              => 'post',
							'type'              => 'post_object',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'post',
							),
							'taxonomy'          => array(),
							'allow_null'        => 0,
							'multiple'          => 0,
							'return_format'     => 'object',
							'ui'                => 1,
						),
					),
				),
				array(
					'key'               => 'field_59ab1614914d6',
					'label'             => 'Extra Principal',
					'name'              => 'vdv_box_1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59ab1696914d7',
							'label'             => 'Título',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 20,
						),
						array(
							'key'               => 'field_59ab16f3914d8',
							'label'             => 'Artigo',
							'name'              => 'post',
							'type'              => 'post_object',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'post',
							),
							'taxonomy'          => array(),
							'allow_null'        => 0,
							'multiple'          => 0,
							'return_format'     => '',
							'ui'                => 1,
						),
					),
				),
				array(
					'key'               => 'field_59a465d32cc4b',
					'label'             => 'Destaques Secundários',
					'name'              => 'vdv_features',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_59c191afafa74',
					'min'               => 1,
					'max'               => 4,
					'layout'            => 'row',
					'button_label'      => '+',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59c191afafa74',
							'label'             => 'Meio',
							'name'              => 'main',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '30',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_59a466652cc4c',
									'label'             => 'Categoria',
									'name'              => 'term',
									'type'              => 'taxonomy',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '70',
										'class' => '',
										'id'    => '',
									),
									'taxonomy'          => 'tema',
									'field_type'        => 'select',
									'allow_null'        => 0,
									'add_term'          => 0,
									'save_terms'        => 0,
									'load_terms'        => 0,
									'return_format'     => 'object',
									'multiple'          => 0,
								),
								array(
									'key'               => 'field_59a466b62cc4d',
									'label'             => 'Qnt.',
									'name'              => 'showposts',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '30',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 5,
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'min'               => 1,
									'max'               => 5,
									'step'              => 1,
								),
							),
						),
						array(
							'key'               => 'field_59c1993abdf16',
							'label'             => 'Lateral',
							'name'              => 'side',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '30',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_59c1993abdf17',
									'label'             => 'Categoria',
									'name'              => 'term',
									'type'              => 'taxonomy',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '70',
										'class' => '',
										'id'    => '',
									),
									'taxonomy'          => 'tema',
									'field_type'        => 'select',
									'allow_null'        => 0,
									'add_term'          => 0,
									'save_terms'        => 0,
									'load_terms'        => 0,
									'return_format'     => 'object',
									'multiple'          => 0,
								),
								array(
									'key'               => 'field_59c1993abdf18',
									'label'             => 'Qnt.',
									'name'              => 'showposts',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '30',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 3,
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'min'               => 1,
									'max'               => 5,
									'step'              => 1,
								),
							),
						),
						array(
							'key'               => 'field_59c19290afa76',
							'label'             => 'Extra',
							'name'              => 'extra',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_59c195a083242',
									'label'             => 'Anúncios?',
									'name'              => 'show_ad',
									'type'              => 'true_false',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '30',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 1,
									'ui'                => 1,
									'ui_on_text'        => 'S',
									'ui_off_text'       => 'N',
								),
								array(
									'key'               => 'field_59c19132fec13',
									'label'             => 'Grupo',
									'name'              => 'ad_side',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_59c195a083242',
												'operator' => '==',
												'value'    => '1',
											),
										),
									),
									'wrapper'           => array(
										'width' => '70',
										'class' => '',
										'id'    => '',
									),
									'choices'           => vdv_get_adrotate_groups(),
									'default_value'     => array(),
									'allow_null'        => 1,
									'multiple'          => 0,
									'ui'                => 1,
									'ajax'              => 0,
									'return_format'     => 'value',
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_59c1914afec14',
									'label'             => 'Título',
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_59c195a083242',
												'operator' => '!=',
												'value'    => '1',
											),
										),
									),
									'wrapper'           => array(
										'width' => '35',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Outros viajantes',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_59c1915dfec15',
									'label'             => 'Artigo',
									'name'              => 'post',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_59c195a083242',
												'operator' => '!=',
												'value'    => '1',
											),
										),
									),
									'wrapper'           => array(
										'width' => '35',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'post',
									),
									'taxonomy'          => array(),
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'object',
									'ui'                => 1,
								),
							),
						),
						array(
							'key'               => 'field_59c19af9b38dd',
							'label'             => 'Anúncios divisores',
							'name'              => 'ad_mid',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => vdv_get_adrotate_groups(),
							'default_value'     => array(),
							'allow_null'        => 1,
							'multiple'          => 0,
							'ui'                => 1,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
					),
				),
				array(
					'key'               => 'field_59c6aecbfd157',
					'label'             => 'Séries Especiais',
					'name'              => 'vdv_specials',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59c6abadfd155',
							'label'             => 'Categoria',
							'name'              => 'term',
							'type'              => 'taxonomy',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '70',
								'class' => '',
								'id'    => '',
							),
							'taxonomy'          => 'serie',
							'field_type'        => 'select',
							'allow_null'        => 0,
							'add_term'          => 0,
							'save_terms'        => 0,
							'load_terms'        => 0,
							'return_format'     => 'object',
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_59c6abb2fd156',
							'label'             => 'Qnt.',
							'name'              => 'showposts',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '30',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 3,
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => 1,
							'max'               => 5,
							'step'              => 1,
						),
					),
				),
				array(
					'key'               => 'field_59a4dcf138ec0',
					'label'             => 'Destinos em Destaque',
					'name'              => 'vdv_destinations',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_59a4dcf138ec1',
					'min'               => 3,
					'max'               => 6,
					'layout'            => 'table',
					'button_label'      => '+',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59a4dcf138ec1',
							'label'             => 'Destino',
							'name'              => 'term',
							'type'              => 'taxonomy',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'taxonomy'          => 'category',
							'field_type'        => 'select',
							'allow_null'        => 0,
							'add_term'          => 0,
							'save_terms'        => 0,
							'load_terms'        => 0,
							'return_format'     => 'object',
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_59a4dd4038ec2',
							'label'             => 'Imagem',
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'id',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'front_page',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'custom_fields',
				4  => 'discussion',
				5  => 'comments',
				6  => 'revisions',
				7  => 'slug',
				8  => 'author',
				9  => 'format',
				10 => 'page_attributes',
				11 => 'featured_image',
				12 => 'categories',
				13 => 'tags',
				14 => 'send-trackbacks',
			),
			'active'                => 1,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5957f98f3dd70',
			'title'                 => 'Parceria',
			'fields'                => array(
				array(
					'key'               => 'field_5823d4fff680a',
					'label'             => 'Título',
					'name'              => 'titulo_box',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33%',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_572e48ba79459',
					'label'             => 'Nome',
					'name'              => 'marca_apoio',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33%',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_572e48ba7ae84',
					'label'             => 'Bio',
					'name'              => 'definicao_apoio',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '34%',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_572e48ba7da14',
					'label'             => 'Descrição',
					'name'              => 'decricao_da_serie',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '66%',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => 5,
					'new_lines'         => 'br',
				),
				array(
					'key'               => 'field_572e48ba7c94d',
					'label'             => 'Avatar',
					'name'              => 'foto_logo_apoio',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '34%',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'post',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'custom_fields',
			),
			'active'                => 1,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5957f9900524d',
			'title'                 => 'Planeje sua viagem',
			'fields'                => array(
				array(
					'key'               => 'field_5693aa87d670a',
					'label'             => 'Destino',
					'name'              => 'vdv_destination',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => 'para …',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_59b552e18b562',
					'label'             => 'Opções',
					'name'              => 'vdv_planning',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_59b553498b564',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => '+',
					'sub_fields'        => array(
						array(
							'key'               => 'field_59b5532c8b563',
							'label'             => 'Imagem',
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'id',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_59b553498b564',
							'label'             => 'Título',
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '35%',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_59b553588b565',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '35%',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_59ecb70f9c7c2',
							'label'             => 'blank',
							'name'              => 'blank',
							'type'              => 'true_false',
							'value'             => null,
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '15%',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 1,
							'ui'                => 1,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_59ecb83d757a9',
							'label'             => 'nofollow',
							'name'              => 'nofollow',
							'type'              => 'true_false',
							'value'             => null,
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '15%',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 1,
							'ui'                => 1,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'post',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_59ecd910e45c7',
			'title'                 => 'Menu Item',
			'fields'                => array(
				array(
					'key'               => 'field_59ecd91b6a054',
					'label'             => 'Ícone',
					'name'              => 'icon_class',
					'type'              => 'select',
					'value'             => null,
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'menu-item--facebook'   => 'Facebook',
						'menu-item--flipboard'  => 'Flipboard',
						'menu-item--googleplus' => 'Google+',
						'menu-item--instagram'  => 'Instagram',
						'menu-item--rss'        => 'RSS',
						'menu-item--twitter'    => 'Twitter',
						'menu-item--youtube'    => 'Youtube',
					),
					'default_value'     => array(),
					'allow_null'        => 1,
					'multiple'          => 0,
					'ui'                => 1,
					'ajax'              => 0,
					'return_format'     => 'value',
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'nav_menu_item',
						'operator' => '==',
						'value'    => 'location/social',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		)
	);

endif;
